# -*- coding: utf-8 -*-
"""PDS2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ak08dAMqlFQ98f5oSeIJ6KJmdlKzp4QZ
"""

import pandas as pd

data=pd.read_csv("/content/train.csv")

data.head()

#Checking for NULL values

data.isna().sum()

d1= pd.DataFrame(data)

"""B)Removing the units from Mileage, Engine, Power and New_Price and converting them into float"""

d1['Mileage'] = d1['Mileage'].str.extract('(\d+\.\d+)').astype(float)

d1['Engine'] = d1['Engine'].str.replace(' CC', '').astype(float)

d1['Power'] = d1['Power'].str.extract('(\d+\.\d+)').astype(float)

d1['New_Price'] = d1['New_Price'].str.extract('(\d+\.\d+)').astype(float)

d1.head()

"""A)Filling missing values in Mileage, Engine, Power with mean values,Seats with mode values"""

d1['Mileage'].fillna(d1['Mileage'].mean(),inplace=True)
d1['Engine'].fillna(d1['Engine'].mean(),inplace=True)
d1['Power'].fillna(d1['Power'].mean(),inplace=True)

d1['Seats'].fillna(d1['Seats'].mode()[0],inplace=True)
d1=d1.dropna()

d1.head()

output_csv_file = 'preprocessed_data.csv'
d1.to_csv(output_csv_file, index=False)

d1.head()

d2=pd.read_csv("/content/preprocessed_data.csv")

d2.isna().sum()

"""Take a look at the unique values for some of our categorical variables: "Fuel_Type," "Transmission," and "Owner_Type."
"""

d2['Fuel_Type'].unique()

d2['Transmission'].unique()

d2['Owner_Type'].unique()

"""C) To work with our categorical variables, we are converting them into numerical data using one-hot encoding.

"""

d2['Fuel_Type'].replace({'Diesel': 0, 'Petrol': 1, 'Electric': 2}, inplace=True)
d2['Transmission'].replace({'Manual': 0, 'Automatic': 1}, inplace=True)
d2['Owner_Type'].replace({'First': 1, 'Second': 2, 'Third': 3, 'Fourth & Above': 4}, inplace=True)

d2.head()

#Save the encoded data in separate csv file

output_csv_file = 'encoded_data.csv'
d2.to_csv(output_csv_file, index=False)

"""D)We are adding a new column called "CURRENT AGE OF THE CAR" to our dataset, which will help us understand how old each car is."""

from datetime import datetime

current_year = datetime.now().year

d2['Current_Age'] = current_year - d1['Year']

#Save the encoded data in separate csv file
output_csv_file = 'newColumnData.csv'
d2.to_csv(output_csv_file, index=False)

d3=pd.read_csv("/content/newColumnData.csv")
d3.head()

"""e)Performing Select,Filter,Rename,Mutate,,Arrange and Summarize

SELECT
"""

selected_columns = d3[['Seats', 'Current_Age', 'Year', 'Mileage', 'Price']]
selected_columns

"""FILTER"""

d3['Mileage'] = pd.to_numeric(d3['Mileage'], errors='coerce')
filtered_data = d3[d3['Mileage'] > 20]
filtered_data

"""RENAME"""

from os import rename

d3.rename(columns={'Year': 'Origin_Year'}, inplace=True)
d3

"""MUTATE"""

current_year = 2024
d3['Age'] = current_year - d3['Origin_Year']
d3

"""ARRANGE"""

sorted_data = d3.sort_values(by='Price', ascending=False)
sorted_data

"""SUMMARIZE"""

average_price_by_make = d3.groupby('Seats')['Price'].mean()
average_price_by_make

d3.head()